project:
  type: website

website:
  title: "**ZHOU ZHANG**"

  navbar:
    logo: logo.png
    background: "#E8E2C8"
    foreground: "#2F4F4F"
    right:
      - text: "**About**"
        href: about.qmd
      - icon: github
        href: https://github.com
      - icon: twitter-x
        href: https://x.com
  back-to-top-navigation: true
  page-footer:
    left: |
      <div style="text-align: left ; font-size: 0.85rem;">
        <i class="bi bi-geo-alt-fill"></i> Monash University,\
        Wellington Road,\
        Clayton, VIC 3800, Australia
      </div>
    right: |
      <div style="text-align: right; font-size: 0.85rem;">
        **ZHUO ZHANG**<br>
        Monash University<br>
        © Copyright 2025 ZHUO ZHANG
      </div>
    foreground: "#2F4F4F"
    background: "#E8E2C8"

format:
  html:
    theme: cosmo
    backgroundcolor: "#F5F5DC"
    textcolor: "#2F4F4F"
    linkcolor: "#2F4F4F"
    include-in-header:
      text: |
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    css: styles.css



